What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
iris_data=pd.read_csv('/content/Iris.csv')

##Array Creation

1. array

    Purpose: Converts a Python list or list of lists into a NumPy array.

In [ ]:
python_list=[1,3,3,4]
a = np.array(python_list)


Shape of the array

In [ ]:
a.shape

(4,)

Rank of the array

In [ ]:
a.ndim

1

2. arange

    Purpose: Returns evenly spaced values within a given interval, similar to Python's range.

In [ ]:
b = np.arange(0, 10, 2)  # Start, Stop, Step
b

array([0, 2, 4, 6, 8])

3. linspace

    Purpose: Returns evenly spaced numbers over a specified interval.

In [ ]:
c = np.linspace(0, 1, 10)  # Start, Stop, Number of points
c


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

4. logspace

    Purpose: Returns numbers spaced evenly on a log scale.

In [ ]:
d = np.logspace(1, 10, num=10, base=2)  # Start (2^1), Stop (2^10), Number of points, Base
d

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

5. zeros

    Purpose: Returns a new array of specified size, filled with zeros

In [ ]:
e = np.zeros((2, 3))  # Shape as a tuple
e

array([[0., 0., 0.],
       [0., 0., 0.]])

6. ones

    Purpose: Returns a new array of specified size and type, filled with ones.

In [ ]:
f = np.ones((3, 3))  # Shape as a tuple
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

7. full

    Purpose: Returns a new array of given shape and type, filled with a specified fill value.

In [ ]:
g = np.full((2, 2), 8)  # Shape and fill value
g

array([[8, 8],
       [8, 8]])

8. eye

    Purpose: Creates an identity matrix (2D array with ones on the diagonal and zeros elsewhere).

In [ ]:
h = np.eye(4)  # Size of the NxN identity matrix
h

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

9. empty

    Purpose: Returns a new array of given shape and type, without initializing entries (contents are random).

In [ ]:
i = np.empty((2, 2))
i

NameError: name 'np' is not defined

###Specifying data types

In [ ]:
x = np.ones(2, dtype=np.int64)
x.dtype

dtype('int64')

#Array Manipulation

1. reshape

    Purpose: Changes the shape of an array without changing its data

In [ ]:
# Convert a couple of columns into a numpy array
sepal_data = iris_data[['SepalLengthCm', 'SepalWidthCm']].values
print(sepal_data.dtype)
print(sepal_data.shape)
reshaped_sepal_data = sepal_data.reshape((300, 1))
print(reshaped_sepal_data.shape)

float64
(150, 2)
(300, 1)


2. ravel

    Purpose: Returns a contiguous flattened array.

In [ ]:
flattened_sepal_data = reshaped_sepal_data.ravel()
print(flattened_sepal_data)
print(flattened_sepal_data.shape)

[5.1 3.5 4.9 3.  4.7 3.2 4.6 3.1 5.  3.6 5.4 3.9 4.6 3.4 5.  3.4 4.4 2.9
 4.9 3.1 5.4 3.7 4.8 3.4 4.8 3.  4.3 3.  5.8 4.  5.7 4.4 5.4 3.9 5.1 3.5
 5.7 3.8 5.1 3.8 5.4 3.4 5.1 3.7 4.6 3.6 5.1 3.3 4.8 3.4 5.  3.  5.  3.4
 5.2 3.5 5.2 3.4 4.7 3.2 4.8 3.1 5.4 3.4 5.2 4.1 5.5 4.2 4.9 3.1 5.  3.2
 5.5 3.5 4.9 3.1 4.4 3.  5.1 3.4 5.  3.5 4.5 2.3 4.4 3.2 5.  3.5 5.1 3.8
 4.8 3.  5.1 3.8 4.6 3.2 5.3 3.7 5.  3.3 7.  3.2 6.4 3.2 6.9 3.1 5.5 2.3
 6.5 2.8 5.7 2.8 6.3 3.3 4.9 2.4 6.6 2.9 5.2 2.7 5.  2.  5.9 3.  6.  2.2
 6.1 2.9 5.6 2.9 6.7 3.1 5.6 3.  5.8 2.7 6.2 2.2 5.6 2.5 5.9 3.2 6.1 2.8
 6.3 2.5 6.1 2.8 6.4 2.9 6.6 3.  6.8 2.8 6.7 3.  6.  2.9 5.7 2.6 5.5 2.4
 5.5 2.4 5.8 2.7 6.  2.7 5.4 3.  6.  3.4 6.7 3.1 6.3 2.3 5.6 3.  5.5 2.5
 5.5 2.6 6.1 3.  5.8 2.6 5.  2.3 5.6 2.7 5.7 3.  5.7 2.9 6.2 2.9 5.1 2.5
 5.7 2.8 6.3 3.3 5.8 2.7 7.1 3.  6.3 2.9 6.5 3.  7.6 3.  4.9 2.5 7.3 2.9
 6.7 2.5 7.2 3.6 6.5 3.2 6.4 2.7 6.8 3.  5.7 2.5 5.8 2.8 6.4 3.2 6.5 3.
 7.7 3.8 7.7 2.6 6.  2.2 6.9 3.2 5.6 2.8 7.7 2.8 6.3

2. concatenate

    Purpose: Joins a sequence of arrays along an existing axis.

In [ ]:
sepal_lengths = iris_data['SepalLengthCm'].values
petal_lengths = iris_data['PetalLengthCm'].to_numpy()
combined_lengths = np.concatenate([sepal_lengths[:, np.newaxis], petal_lengths[:, np.newaxis]], axis=1)
combined_lengths

4. vstack

    Purpose: Stacks arrays in sequence vertically (row wise).

In [ ]:
vertical_stack = np.vstack([sepal_lengths, petal_lengths])
vertical_stack

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
        1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       

5. hstack

    Purpose: Stacks arrays in sequence horizontally (column wise).

In [ ]:
horizontal_stack = np.hstack([sepal_lengths[:, np.newaxis], petal_lengths[:, np.newaxis]])
horizontal_stack

6. split

    Purpose: Splits an array into multiple sub-arrays.

In [ ]:
split_arrays = np.split(combined_lengths, 10)
split_arrays

##Array Indexing Examples

1. Basic Indexing

    Purpose: Accessing specific elements or slices of an array.

In [ ]:
basic_indexing_example = iris_data[['SepalLengthCm', 'SepalWidthCm']].to_numpy()
basic_indexing_example.shape

(150, 2)

In [ ]:
basic_indexing_example[10:20,1]

array([3.7, 3.4, 3. , 3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8])

##Mathematical Functions

1. Basic Arithmetic

    Purpose: Perform element-wise arithmetic operations.

In [ ]:
iris_array = iris_data.iloc[:, 1:5].to_numpy()
iris_array.shape

(150, 4)

In [ ]:
basic_indexing_array = iris_array[:5, :2]
basic_indexing_array

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [ ]:
boolean_indexing_array = iris_array[:, :] > 4.0
boolean_indexing_array

In [ ]:
fancy_indexing_array = iris_array[[0, 49, 99], :]
fancy_indexing_array

array([[5.1, 3.5, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.7, 2.8, 4.1, 1.3]])

##Mathematical Functions

1. Mean Calculation

    Purpose: Compute the average of an array

In [ ]:
mean_sepal_width = np.mean(iris_array[:, 1])
mean_sepal_width

3.0540000000000003

In [ ]:
std_petal_length = np.std(iris_array[:, 2])
std_petal_length

1.7585291834055212

2. Matrix Multiplication (Dot Product)

    Purpose: Compute the dot product of two arrays.

In [ ]:
dot_product_matrix = np.dot(iris_array.T, iris_array)
dot_product_matrix

array([[5223.85, 2670.98, 3484.25, 1127.65],
       [2670.98, 1427.05, 1673.91,  531.53],
       [3484.25, 1673.91, 2583.  ,  868.97],
       [1127.65,  531.53,  868.97,  302.3 ]])

argmin

Purpose: Find the index of the minimum value in an array.

In [ ]:
min_index = np.argmin(iris_array[:, 2])  # Find the index of the shortest petal length
min_index

22

In [ ]:
max_index = np.argmax(iris_array[:, 2])  # Find the index of the longest petal length
max_index

118

In [ ]:
# Assuming another matrix of compatible dimensions
random_matrix = np.random.rand(4, 3)  # Creating a 4x3 random matrix
product = np.matmul(iris_array, random_matrix)  # Matrix multiplication
product

In [ ]:
random_numbers = np.random.rand(5)
# random_numbers = np.random.rand(5,3,2)   # Generate 5 random numbers
random_numbers

array([0.02223664, 0.06210252, 0.27388704, 0.51743311, 0.13777968])

In [ ]:
random_normal = np.random.randn(5)  # Generate 5 random numbers from normal distribution
random_normal

array([ 0.02365395, -0.25000691, -0.30912751, -1.70770377,  0.46727357])

In [ ]:
random_integers = np.random.randint(1, 10, 5)  # Generate 5 random integers between 1 and 9
random_integers

array([8, 1, 4, 2, 3])